### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'replay_memory/memory.pkl'

### ISSUE THREAD

**Issue by ziryawulawo** [FelippeRoza/carla-rl#3]
Traceback (most recent call last):
  File "C:\Users\DELL\Anaconda3\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\DELL\Anaconda3\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\finalproject\PythonAPI\examples\rl_agent.py", line 223, in control_loop
    train_loop(rl_config, vehicle, map, sensors)
  File "C:\finalproject\PythonAPI\examples\rl_agent.py", line 72, in train_loop
    memory = memory.load_memory(rl_config.memory_load_path)
  File "C:\finalproject\PythonAPI\examples\rl_utils.py", line 451, in load_memory
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'replay_memory/memory.pkl'

**Comment by HFY123** [comment]
I met the same problem, have you fixed it?
